name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_output:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Instalar dependencias necesarias para compilación
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    # Paso 3: Ejecutar el Makefile inicial en el directorio raíz
    - name: Build the main project
      run: make

    # Paso 4: Ejecutar el Makefile en el directorio /test
    - name: Build tests
      run: |
        cd test
        make
        make bonus

    # Paso 5: Ejecutar el archivo ./test y capturar la salida
    - name: Run tests and capture output
      run: |
        cd test
        ./test > program_output.txt

    # Paso 6: Verificar si la salida contiene el color rojo (\033[31m)
    - name: Check for red color in output
      run: |
        cd test
        if grep -q $'\033[31m' program_output.txt; then
          echo "Error: The is at least 1 test that didnt pass"
          exit 1
        else
          echo "All tests OK"
        fi
